version: '3'

services:
  postgres:
    image: postgres:14.5-alpine
    container_name: 'java_postgres'
    ports:
      - "35100:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tink
  app:
    build: ./
    container_name: 'tink-app'
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/tink
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - postgres
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
    volumes:
      - minio-data:/data
    command: "server /data"
    healthcheck:
      test: timeout 5s bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1
      interval: 5s
      retries: 1
      timeout: 5s
    ports:
      - '9002:9000'
    networks:
      - shared-network

volumes:
  minio-data:

networks:
  shared-network:
    external: true